### ISSUE TITLE
double-check concept linking

### ISSUE THREAD

**Issue by LinguList** [lexibank/bodtkhobwa#14]
Concepts need to be double-checked, also with new concepts we want to add to concepticon, currently with an asterisk `*`.

**Comment by xrotwang** [comment]
When do we want to make a move of new lists from concepticon-dev to concepticon-data? With the DiACL lists mostly done, I'd say we already have enough to move?

**Comment by LinguList** [comment]
Yes, for a first test on how this works, definitely. 

Question is: do we want to make a small procedure to:

- pull out all new lists from concepticon-dev

and

- extract those concepts with star

and

- create the new (empty) lines in concepticon.tsv, so one can add definitions? 

Or do we do that manually? As we already have the relink-command in concepticon, it would be smooth, if only we create numbers for the concepts, right?

**Comment by xrotwang** [comment]
Should be a concepticon command, I think: https://github.com/concepticon/pyconcepticon/issues/1

**Comment by tresoldi** [comment]
This was fixed with 2fb1c6b7b59d779ae5f808d007d4da2d3ac80f0d
