### ISSUE TITLE
add partial cognates and morpheme tags

### ISSUE THREAD

**Issue by LinguList** [lexibank/bodtkhobwa#15]
The data is a good example for cldf in extended versions, and it contains:

- morpheme boundaries, to which morpheme tags are attached (all checked)
- partial cognates
- partial alignments

So we should be able to see here how well lexibank can account for these enhanced ways of annotation. And also if we can compute extract these things and convert them to cldf without major efforts.

**Comment by LinguList** [comment]
I assigned @xrotwang here, as you know best how we discussed to handle those things in cldf (and I am less sure here).

**Comment by xrotwang** [comment]
@LinguList quick question: A row like this
```
ID	ALIGNMENT	COGIDS	CONCEPT	CONCEPT_IN_SOURCE	CROSSIDS	DOCULECT	FORM	MORPHEMES	NEW	NOTE	ROOTIDS	STRUCTURE	TOKENS	VALUE
17	n a + l + tʰ e -	5 4	2pl.incl	2pl.incl	5 3 4	Khispi	nal+tʰe	2PL _excl1 _PL1		additive focus	5 2 4	i n + i + i n	n a + l + tʰ e	nal-tʰe
```
means "the two morphemes `nal` and `tʰe` belong to cognate sets `5` and `4` respectively"?

What do `CROSSIDS` and `ROOTIDS` mean? Are roots a variant of cognacy - and should also be encoded in CLDF?

**Comment by LinguList** [comment]
Yes, exactly, but our reference column is "crossids" now, for the reason that these are "cross-semantic" cognate sets (a technical thing, as we start from same-semantic cognates, for practical reasons). 

The rootids are an idea for the future: if something is not alignable, as it has changed due to morphology or irregular sound change, or whatever, but we assume it's still cognate (also suppletion, like "go" vs. "went", potentially), so "etymologically alike", we assign it the same rootid, but we assume that all crossids should be perfectly alignable, while rootids may not. 

Cogids are intermediate now, and can be automatically produced from the crossids, but we did not do this here, when submitting this data to osf (should've though, I guess).

The Morphemes column is futhermore important, as it gives a gloss on each morpheme, so it explains each of the three morphemes in some way similar to inter-linear-glossed text, using space as segmentation.

**Comment by LinguList** [comment]
Ah, one more thing: structure column is giving an interpretation of the phonotactics of the string, something we also added to cldf already, but never exemplified properly. Here, the (arbitrary) strings say: if a character, like "i" is the same, this means the phonotactic position is the same (like "i" = "initial", "n" = "nucleus", etc.). But maybe we can skip that for the time being.

**Comment by xrotwang** [comment]
ok, so the example I gave has actually 3 morphemes, in cognatesets `5 3 4` respectively? The morpheme segmentation would then fall out of the `TOKENS` column by splitting on `+`, correct? I misread the value of form `nal+tʰe` as belonging to the `MORPHEMES` column before. The `2PL _excl1 _PL1` in `MORPHEMES` would rather be a gloss, then?

**Comment by LinguList** [comment]
Yes, it has three morphemes, TOKENS is the reference. CROSSIDS gives the three cognate sets (0 meaning: no assignment), splitting on + for tokens, and on space for crossids, etc. Teh 2PL, etc., is a gloss, yes. Like an explanation on a complex word.

**Comment by xrotwang** [comment]
So if we wanted to go CLDF with bells and whistles we could even add morphemes and glosses and meaning (as translation) using an [Examples](https://github.com/cldf/cldf/tree/master/components/examples) component?

**Comment by LinguList** [comment]
I'd say this is not necessarily an "example", but a historical analysis, in line with our specs in the [FormTable](https://github.com/cldf/cldf/tree/master/components/forms), where:

* MORPHEMES -> MotivationStructure (maybe a bad term)
* STRUCTURE -> [ProsodicStructure](http://cldf.clld.org/v1.0/terms.rdf#prosodicStructure)

But the MotivationStructure is indeed close to a "gloss".

**Comment by xrotwang** [comment]
ah, ok. Yes, representing it as IGT would only make sense if the glosses would also adhere to the standard list of the Leipzig Glossing Rules.
