### ISSUE TITLE
Fix curation warnings

### ISSUE THREAD

**Issue by chrzyki** [lexibank/bodtkhobwa#19]
The REPL spits a number of warnings, e.g.

> [WARNING] Problem with row 821 in col 1, expected «<function <lambda> at 0x7f7279777488>» as datatype but received «249 ? 250»  (ROW: pʰ yː + tɕʰ u - + l u ŋ|249 ? 250|cockroach|cockroach|249 685 250|Khoitam|ʨʰu+luŋ|INSECT1 COCKROACH1 COCKROACH2|||570 685 250|i n + i n + i n c|pʰ yː + tɕʰ u + l u ŋ|(pʰyː) ʨʰu-luŋ, entry cogids).

during the `makecldf` call. This should ideally be addressed before the SDATA submission to make the reproducible run 'more clean'.

**Comment by LinguList** [comment]
Yes, this is a lingpy warning, that means that we have cognate ids which are not an integer. This can be avoided by applying some hack from within lingpy, or by changing the name of the ogid field. It's not dramatic though, as the COGID is not being used.
