### ISSUE TITLE
Use released version of authoritative catalog repos for releases

### ISSUE THREAD

**Issue by xrotwang** [lexibank/bodtkhobwa#22]
It looks like a fork of `concepticon/concepticon-data` and a non-released commit is used here:
https://github.com/lexibank/bodtkhobwa/blob/288d281a7ab05dd1a1698125c39dda1ede35a0a2/cldf/cldf-metadata.json#L31-L32

**Comment by xrotwang** [comment]
I think it would be good practice to use clones of the original repos, and only release tags.

**Comment by xrotwang** [comment]
Maybe it's even a good idea to use a special, read-only clone of the catalogs for dataset creation. With `cldfbench catconfig` that should be relatively easy to achieve.

**Comment by LinguList** [comment]
Yes, but if I am "developing" datasets, I have to change in multiple directions, and in those cases, I am reluctant of fixing one thing, as it may often appear that I have to change, e.g., something in Concepticon as well. As this is not yet released, I guess, it is enough to account for that, once all repos are in place.

**Comment by xrotwang** [comment]
Yes, using a read/write repos is fine as well - although it might require more attention. But I would **not** use personal forks of the repositories, because that makes tracing provenance a lot harder.

**Comment by LinguList** [comment]
Yes, that's fine, I'll switch to that. I just need to get used to it, as before the personal fork was the standard, and now I need to slowly get my data adjusted.

**Comment by SimonGreenhill** [comment]
Fixed here: https://github.com/lexibank/bodtkhobwa/commit/ba8ef3850a9b63fafdc216a1f39854b80e7ed099
