### ISSUE TITLE
Opt-in dataset for cross-concept cognates

### ISSUE THREAD

**Issue by chrzyki** [lexibank/bodtkhobwa#23]
See https://github.com/lexibank/pylexibank/commit/2533f67b43a9c943fc06d39f1f8c1d164e858f50#diff-7437d82378d1fce6944dd496b80307bf.

Should I have a look at the cross-concept cognates @LinguList or do you think that won't be necessary? There a couple of interesting ones: *belly*-*belt*-*fruit*, *horse*-*frog*, *empty*-*head*-*knee*-*lungs*, etc.

**Comment by LinguList** [comment]
As far as I remember, we coded these cross-concept-wise.

**Comment by chrzyki** [comment]
Ok, thanks! I'll just leave this open to explicitly flag this for buildbot & Co.

**Comment by LinguList** [comment]
Yes, just checked it again: the cross-ids are all beautiful partial cognates. If pairs look strange: it is because they are partial cognates, and there you can have semantic differences, because two nouns share "ablative case".

**Comment by chrzyki** [comment]
Cool, thanks for checking again. I'll keep this dataset in mind as an example for this. Will leave the issue open until we have a new `pylexibank` release and we can flag the data for cross-concept cognates.

**Comment by monpasang** [comment]
You could also ask someone who knows about these languages what these cross-semantic cognates are and what they mean or imply.
