### ISSUE TITLE
Name of author

### ISSUE THREAD

**Issue by monpasang** [lexibank/bodtkhobwa#26]
My name is Timotheus Adrianus Bodt. Not Timothaeus Adrianus Bodth.

**Comment by monpasang** [comment]
My ORCID ID is 0000-0002-2024-0488

**Comment by monpasang** [comment]
My name is, among other places, misspelled with:

Data curator(s)

Rights holder(s)

In the file Contributors (MD)

In the file README (MD)

**Comment by LinguList** [comment]
This has been accounted for in CONTRIBUTORS.md, README will be automatically modified.

**Comment by monpasang** [comment]
Ok.
