### ISSUE TITLE
Funding agency

### ISSUE THREAD

**Issue by monpasang** [lexibank/bodtkhobwa#27]
This work was funded by

Schweizerischer Nationalfonds zur Förderung der Wissenschaftlichen Forschung: Strategische Zielsetzungen im Subkontinent (100015_138331)

and 

Schweizerischer Nationalfonds zur Förderung der Wissenschaftlichen Forschung: ‘Reconstruction of Proto-Western Kho-Bwa’ (Early Postdoc.Mobility-Stipendium Nr. P2BEP1_181779)

among others.

**Comment by LinguList** [comment]
Please have a look at the file [NOTES.md](https://github.com/lexibank/bodtkhobwa/blob/master/NOTES.md). You have edit rights and can modify the information here (modifying the README.md is not recommended, as the code will overwrite the changes). Please edit this file as you see fit, if there are more funding agencies or you want to provide other information.

**Comment by monpasang** [comment]
Ok looks fine.
