### ISSUE TITLE
Wikipedia reference

### ISSUE THREAD

**Issue by monpasang** [lexibank/bodtkhobwa#29]
On Wikipedia (https://en.wikipedia.org/wiki/Kho-Bwa_languages), this CLDF dataset is referred to as:

Johann-Mattis List, Mei Shin Wu, Robert Forkel, & Tiago Tresoldi. (2019). lexibank/bodtkhobwa: Lexical Cognates in Western Kho-Bwa (Version v2.0) [Data set]. Zenodo. doi:10.5281/zenodo.3537604

This should be:

Timotheus A. Bodt, & Johann-Mattis List. (2019). CLDF dataset derived from Bodt's "Lexical Cognates in Western Kho-Bwa" from 2019 (Version v2.0) [Data set]. Zenodo. http://doi.org/10.5281/zenodo.3537604

**Comment by LinguList** [comment]
Wikipedia will update the quotes once the users see that this has been wrongly quoted. The alterntive is to to update it oneself, but one needs a wikipedia account and ideally some credibility.

**Comment by monpasang** [comment]
This just shows how incredibly unreliable Wikipedia is. Anyone can basically put anything there. 

I have neither a Wikipedia account nor credibility. Maybe I should make one and start cleaning up some mess here and there.
